logging:
  level:
    root: INFO

server:
  port: ${SERVER_PORT}

spring:
  application:
    name: news
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        hbm2ddl:
          auto: none
        ddl-auto:
          none
        dialect: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      
rest:
  client:
    auth-server: ${AUTH_SERVER}

token:
  signing:
    key: ${SIGNING_TOKEN}